services:
  - type: web
    name: rankitpro-web
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rankitpro-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
        
databases:
  - name: rankitpro-db
    databaseName: rankitpro
    user: rankitpro