services:
  - type: web
    name: rank-it-pro
    env: node
    plan: starter
    buildCommand: ./deploy-build.sh
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: REPLIT_KEEP_PACKAGE_DEV_DEPENDENCIES
        value: "1"
    autoDeploy: false