services:
  - type: web
    name: rankitpro
    env: node
    plan: starter
    buildCommand: rm -rf node_modules && npm install && node render-deploy.mjs
    startCommand: cd dist && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rankitpro-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: rankitpro-db
    databaseName: rankitpro
    user: rankitpro
    plan: starter