services:
  - type: web
    name: rankitpro
    env: node
    plan: starter
    buildCommand: rm -rf node_modules && npm install && node deploy-truly-final.js
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: rankitpro-db
    databaseName: rankitpro
    user: rankitpro
    plan: starter