services:
  - type: web
    name: rankitpro-saas
    env: node
    plan: starter
    buildCommand: npm ci --omit=optional || npm install --omit=optional --legacy-peer-deps && chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rankitpro-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

databases:
  - name: rankitpro-db
    databaseName: rankitpro
    user: rankitpro_user
    plan: starter