services:
  - type: web
    name: rank-it-pro-saas
    runtime: node
    plan: starter
    region: oregon
    buildCommand: |
      # Install dependencies including previously missing ones
      echo "📦 Installing dependencies..."
      npm install --ignore-optional --no-optional
      
      # Install external dependencies that caused bundling failures
      echo "🔧 Installing external dependencies..."
      npm install @babel/preset-typescript lightningcss @rollup/rollup-linux-x64-gnu --save-dev --ignore-optional
      
      # Run production build with ESBuild bundling fixes
      echo "🚀 Running production build with bundling fixes..."
      bash production-build.sh
      
      echo "✅ Production build completed successfully"
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: rank-it-pro-db
          property: connectionString
    healthCheckPath: /api/health
    
databases:
  - name: rank-it-pro-db
    databaseName: rank_it_pro
    user: rank_it_pro_user
    region: oregon
    plan: starter