/**
 * Advanced Backlink Generation System for RankItPro
 * Generates high-quality backlinks with varied anchor text and strategic placement
 */

export interface BacklinkConfig {
  showBacklink: boolean;
  backlinkStyle: 'minimal' | 'branded' | 'contextual' | 'rich';
  anchorVariation: 'powered_by' | 'business_management' | 'field_service' | 'reviews_platform' | 'random';
  includeSchema: boolean;
  customAnchorText?: string;
}

export class BacklinkGenerator {
  private static readonly ANCHOR_VARIATIONS = {
    powered_by: [
      'Powered by Rank It Pro',
      'Built with Rank It Pro',
      'Generated by Rank It Pro',
      'Created with Rank It Pro'
    ],
    business_management: [
      'Business Management by Rank It Pro',
      'Field Service Management Platform',
      'Professional Service Management',
      'Customer Management Software'
    ],
    field_service: [
      'Field Service Software',
      'Technician Management Platform',
      'Service Business Platform',
      'Professional Field Operations'
    ],
    reviews_platform: [
      'Review Management Platform',
      'Customer Review System',
      'Online Reputation Management',
      'Review Automation Platform'
    ]
  };

  private static readonly BRANDED_LINKS = {
    minimal: {
      html: '<div class="rip-attribution"><a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Business Management Platform">__ANCHOR__</a></div>',
      css: '.rip-attribution { text-align: center; margin-top: 15px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #6b7280; }'
    },
    branded: {
      html: `
        <div class="rip-brand-footer">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 2L2 7v10c0 5.55 3.84 9.74 9 11 5.16-1.26 9-5.45 9-11V7l-10-5z"/>
          </svg>
          <a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Professional Business Management Platform">__ANCHOR__</a>
        </div>
      `,
      css: '.rip-brand-footer { display: flex; align-items: center; justify-content: center; gap: 6px; margin-top: 15px; padding: 10px; background: #f8fafc; border-radius: 6px; font-size: 12px; color: #6b7280; } .rip-brand-footer svg { opacity: 0.7; }'
    },
    contextual: {
      html: '<div class="rip-context"><span>Customer testimonials managed by</span> <a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Customer Review Management Platform">__ANCHOR__</a></div>',
      css: '.rip-context { text-align: center; margin-top: 15px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #9ca3af; } .rip-context a { color: #3b82f6; font-weight: 500; }'
    },
    rich: {
      html: `
        <div class="rip-rich-footer">
          <div class="rip-logo-section">
            <div class="rip-logo">R</div>
            <div class="rip-info">
              <a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Complete Business Management Platform">__ANCHOR__</a>
              <div class="rip-tagline">Complete business management solution</div>
            </div>
          </div>
        </div>
      `,
      css: '.rip-rich-footer { margin-top: 20px; padding: 15px; background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%); border-radius: 8px; } .rip-logo-section { display: flex; align-items: center; gap: 10px; } .rip-logo { width: 32px; height: 32px; background: #3b82f6; color: white; border-radius: 6px; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 14px; } .rip-info a { color: #1f2937; font-weight: 600; font-size: 13px; text-decoration: none; } .rip-tagline { color: #6b7280; font-size: 11px; margin-top: 2px; }'
    }
  };

  /**
   * Generate a backlink with schema markup and varied anchor text
   */
  static generateBacklink(config: BacklinkConfig, companyName?: string): { html: string; css: string; schema?: string } {
    if (!config.showBacklink) {
      return { html: '', css: '' };
    }

    const anchorText = this.getAnchorText(config, companyName);
    const linkTemplate = this.BRANDED_LINKS[config.backlinkStyle];
    
    const html = linkTemplate.html.replace('__ANCHOR__', anchorText);
    const css = linkTemplate.css;

    let schema = '';
    if (config.includeSchema) {
      schema = this.generateSchema(companyName);
    }

    return { html, css, schema };
  }

  /**
   * Get varied anchor text based on configuration
   */
  private static getAnchorText(config: BacklinkConfig, companyName?: string): string {
    if (config.customAnchorText) {
      return config.customAnchorText;
    }

    if (config.anchorVariation === 'random') {
      // Pick random variation from all categories
      const allVariations = Object.values(this.ANCHOR_VARIATIONS).flat();
      return allVariations[Math.floor(Math.random() * allVariations.length)];
    }

    const variations = this.ANCHOR_VARIATIONS[config.anchorVariation] || this.ANCHOR_VARIATIONS.powered_by;
    return variations[Math.floor(Math.random() * variations.length)];
  }

  /**
   * Generate schema markup for better SEO
   */
  private static generateSchema(companyName?: string): string {
    return `
      <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "WebApplication",
        "name": "Rank It Pro",
        "url": "https://rankitpro.com",
        "applicationCategory": "BusinessApplication",
        "operatingSystem": "Web",
        "description": "Complete business management platform for field service companies, restaurants, healthcare practices, and professional services.",
        "provider": {
          "@type": "Organization",
          "name": "Rank It Pro",
          "url": "https://rankitpro.com"
        },
        "offers": {
          "@type": "Offer",
          "category": "SaaS",
          "businessFunction": "Business Management"
        }
      }
      </script>
    `;
  }

  /**
   * Generate contextual backlinks for different content types
   */
  static generateContextualBacklink(contentType: 'review' | 'testimonial' | 'blog' | 'checkin', companyName?: string): string {
    const contexts = {
      review: `Customer reviews collected and displayed using <a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Review Management Platform">Rank It Pro's review management system</a>`,
      testimonial: `Testimonials managed by <a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Customer Testimonial Platform">Rank It Pro</a>`,
      blog: `Content created with <a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="AI Content Generation Platform">Rank It Pro's AI content system</a>`,
      checkin: `Service updates powered by <a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Field Service Management">Rank It Pro</a>`
    };

    return `<div class="rip-contextual" style="margin-top: 10px; padding: 8px; background: #f9fafb; border-radius: 4px; font-size: 10px; color: #9ca3af; text-align: center;">${contexts[contentType]}</div>`;
  }

  /**
   * Generate backlink for WordPress/CMS integration
   */
  static generateWordPressBacklink(style: 'footer' | 'sidebar' | 'inline' = 'footer'): string {
    const styles = {
      footer: {
        html: `
          <div class="rankitpro-attribution">
            <p><a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Business Management Platform">Professional business management</a> by Rank It Pro</p>
          </div>
        `,
        css: '.rankitpro-attribution { margin: 20px 0; text-align: center; font-size: 12px; color: #666; } .rankitpro-attribution a { color: #0073aa; text-decoration: none; }'
      },
      sidebar: {
        html: `
          <div class="widget rankitpro-widget">
            <h4 class="widget-title">Business Management</h4>
            <div class="widget-content">
              <p>Powered by <a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Complete Business Management Solution">Rank It Pro</a> - the complete solution for managing your business operations, customer reviews, and field service teams.</p>
            </div>
          </div>
        `,
        css: '.rankitpro-widget { background: #f9f9f9; padding: 15px; border-radius: 5px; margin-bottom: 20px; } .rankitpro-widget .widget-title { margin: 0 0 10px 0; font-size: 16px; color: #333; } .rankitpro-widget p { margin: 0; font-size: 13px; line-height: 1.5; } .rankitpro-widget a { color: #0073aa; }'
      },
      inline: {
        html: '<span class="rankitpro-inline">(<a href="https://rankitpro.com" target="_blank" rel="noopener nofollow" title="Business Management Platform">Rank It Pro</a>)</span>',
        css: '.rankitpro-inline { font-size: 11px; color: #999; } .rankitpro-inline a { color: #0073aa; }'
      }
    };

    return styles[style].html + '<style>' + styles[style].css + '</style>';
  }

  /**
   * Get default backlink configuration
   */
  static getDefaultConfig(): BacklinkConfig {
    return {
      showBacklink: true,
      backlinkStyle: 'minimal',
      anchorVariation: 'powered_by',
      includeSchema: false
    };
  }

  /**
   * Generate analytics tracking for backlinks
   */
  static generateTrackingCode(source: string, medium: string = 'widget'): string {
    return `?utm_source=${encodeURIComponent(source)}&utm_medium=${encodeURIComponent(medium)}&utm_campaign=widget_backlink&utm_content=attribution`;
  }
}